### ISSUE TITLE
Tickets still able to be purchased even when event is restricted to membership level

### ISSUE THREAD

**Issue by rmsilver7** [strangerstudios/pmpro-events#18]
Using The Events Calendar plugin and when I have an event restricted to a specific membership level it is still showing the info to purchase tickets underneath the notice that you need to register to see that content. 

![tickets-still-shown](https://user-images.githubusercontent.com/43621346/58689771-c81b0080-833c-11e9-85b4-9bfadaa51f7e.jpg)

**Comment by andrewlimaza** [comment]
Hi there,

I have just run some further tests on my local environment and I was unable to recreate this issue. When did you start using the PMPro Events plugin, we haven't started adjusting the Add Ons version number yet as this plugin is still in development.

I tested this using the latest version of The Events Calendar (4.9.2) and Event Tickets (4.10.6). The RSVP section is hidden for non-members.

Do you have any other specific settings enabled for the Events Tickets plugin that I may test on my end?

**Comment by rmsilver7** [comment]
@andrewlimaza The RSVP and event details are being hidden, but the tickets block is not. 

I took over this site while it's still in development, this was already installed, but I went ahead and pulled the latest version on 5/29 and reinstalled it. Looks like we are running:

The Events Calendar 4.9.2
The Events Calendar PRO 4.7.2
Event Tickets 4.10.6
Event Tickets PLUS 4.10.5

As for settings, I don't think there is anything to weird but here are a few that might be different from default: 

Display > Basic Template Settings: using Tribe Events Style
Display > Basic Template Settings: Enable the Month View Cache is check marked

**Comment by andrewlimaza** [comment]
Thanks for the feedback, would you mind reaching out via our contact form so I may assist you further?

www.paidmembershipspro.com/contact

**Comment by rmsilver7** [comment]
I sent in the Pro and Plus versions of the plugins a couple days ago. This is the only thing holding us up from going live. Any ideas when you will be able to take a look?

**Comment by AnsieLima** [comment]
Hi Riika,
Just to confirm, did you reply to me at ansie@paidmembershipspro.com or send it to info@paidmembershipspro. I checked under our corresponding email thread and in our email database and can't seem to find it.

**Comment by rmsilver7** [comment]
The first time I sent it I just replied to the email that was sent to me. Tonight I sent it directly to your email address. I then also replied to the ticket saying I resent it and I haven’t gotten any type of response to either email.

**Comment by andrewlimaza** [comment]
I have just tested this and I am unable to recreate the issue. The tickets are being hidden for restricted events for me.

I tested this while being logged-in without a membership level and being logged-out.

**Comment by andrewlimaza** [comment]
This plugin hasn't been officially released yet and should be released in the near future. I'd recommend in opening up a support ticket on www.paidmembershipspro.com on our premium support forums to get a more in-depth assistance with this.

Thank you for your patience and understanding.

**Comment by rmsilver7** [comment]
I figured out the problem. I was logged in as an admin (though I don't have a membership level assigned to my admin account) and then it still allowed me to add it to cart. Once I viewed the page as someone not logged in it said I needed to login to purchase.
