### ISSUE TITLE
Requirement: Ensure RSS feeds are properly filtered according to advanced settings

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/pmpro-events#21]

**Comment by kimcoleman** [comment]
Events Manager: 
- Working: If you have the advanced setting set to filter searches and archives, the RSS feed is properly filtered.
- Open Issue: If you manually add the #_EVENTEXCERPT placeholder to your Event RSS feed content, it will show regardless of advanced setting. Default content is also always included: date, time, location info.

**Comment by kimcoleman** [comment]
The Events Calendar:
- Working: If you have the advanced setting set to filter searches and archives, the RSS feed is properly filtered.
- Open Issue: Excerpts are automatically shown in the feed, so even if you have your advanced setting to hide excerpts, it is still included in the RSS feed. Feed is also showing the event date (maybe OK?)

**Comment by andrewlimaza** [comment]
This is okay for now, going to close it. If support tickets come up with issues we can relook this. I believe PMPro will handle this correctly if Events plugins are using the default filters.

There seems to be limitations inside Events plugins to filter the XML output etc.
