### ISSUE TITLE
Bug: Sugar Calender event date doesn't display

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/pmpro-events#26]
When using Sugar Calendar (lite) and PMPro Addons plugin is installed and activated the date for events does not display.

**Comment by andrewlimaza** [comment]
For now user's should remove the filter `remove_filter( 'pmpro_has_membership_access_filter', 'pmpro_events_sugar_calendar_has_membership_access', 10, 4 );`

There's an update coming out shortly that fixes another bug with Sugar Calendar, I'm going to close this ticket as resolved as this will be available in the updated version.
