### ISSUE TITLE
The Events Calendar: Member events displayed in archive view to non-members

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/pmpro-events#27]
Need to filter the display of the post content for a restricted event on the "archive" page (/events) in list or calendar view.

The Single Event is properly respecting Advanced Settings (whether to show excerpts or hide).

To reproduce:

- Install and activate The Events Calendar.
- Install and activate Paid Memberships Pro
- Check Memberships > Settings > Advanced tab that "Filter searches and archives" and "Show Excerpts to Non-Members" set to members only.
- Create a membership level
- Install and active Paid Memberships Pro - Events Add On
- Create Event
- Visit events pages as non-member
- Click on "Now onwards" and select historic date
- Members only events are now listed.

![CmumYghn4g](https://user-images.githubusercontent.com/9744519/77764477-5fc4aa80-7045-11ea-96bb-6496d5495c43.gif)
![firefox_iem3fVdylO](https://user-images.githubusercontent.com/9744519/77764483-62bf9b00-7045-11ea-9efd-ae3d08c9eca8.png)

**Comment by andrewlimaza** [comment]
**UPDATE**
I've recreated something similar.

On initial load, it shows the events but then if you refresh the page it is hidden correctly.

**Comment by andrewlimaza** [comment]
This issue only occurs when switching views from List > Month > Day etc.

**Comment by andrewlimaza** [comment]
Looking into this, it seems that the Events Calendar uses AJAX to switch between views and the content doesn't get filtered by the WP Query.

**Comment by andrewlimaza** [comment]
Ref: `tribe_repository_default_query_args` filter.
