### ISSUE TITLE
BUG: Single Events page appear blank when they should show Excerpt (The Events Calendar)

### ISSUE THREAD

**Issue by kimwhite** [strangerstudios/pmpro-events#38]
Since the most recent update to 1.1  EVENTS will show up in the list or menu, but if clicked on, they take you to a blank single event page.   Should show excerpt and "pmpro message".

Recreated with a clean install.  Only PMPro, The Events Calendar, and Events for Members-Only Add On.
Settings in PMPro Advanced Settings to SHOW experts and not hide from search.

Single page events with a required level appeared fine at first, including excerpt and message, but when I began changing events or applying categories, the main content stopped showing title, excerpt, and message.
![blank-except-in-schema](https://user-images.githubusercontent.com/8083630/112166797-56254280-8bc6-11eb-9f01-312f8a6bb0c3.png)

**Comment by andrewlimaza** [comment]
A couple of notes here:

* This only affects the Block Editor (sometimes).
* While debugging the code https://github.com/strangerstudios/pmpro-events/blob/dev/modules/the-events-calendar.php#L149-L163 and var_dump around the excerpt functions it 'cleared' and started to show the excerpt again for non-members for events. Once this var_dump was in place, things were working as intended throughout.

This seems to be more of an issue with The Events Calendar plugin than Paid Memberships Pro. I'm not sure if there's template caching/AJAX loading that's causing this to get out of sync.

**Comment by sc0ttkclark** [comment]
I'm not 100% sure here, but https://github.com/strangerstudios/pmpro-events/pull/40 may also address this bug. Needs further testing to be sure.
