### ISSUE TITLE
Shows excerpt for last entered event as excerpt for all events in list of The Events Calendar

### ISSUE THREAD

**Issue by SheraPoet** [strangerstudios/pmpro-events#39]
Using Event Tickets by The Events Calendar V 5.1.1, Paid Membership Pro V 2.5.7, Paid Memberships Pro - Member Directory Add On V 1.1
When PM Pro Events Add-On is activated the Events Calendar (list view) shows the same excerpt for all the events - using the excerpt from the last entered event. When deactivated shows proper excerpts for each event.
I wanted to restrict info in the event listing to not show the Events Calendar RSVP or ticket option altogether to non-members or non-logged-in-members but as a workaround I have kept the PM pro events deactivated and in Events Calendar, under the Events Settings Tickets tab I check off "Require users to log in before they RSVP" under Login Requirements. However, this option adds a "Login to RSVP" option over the RSVP box, unrelated to PM Pro. When a user clicks on that it opens a Wordpress login screen, not the stylized Membership Login screen which integrates with the site, as I would prefer. It confuses the members a bit.

**Comment by sc0ttkclark** [comment]
This will be addressed in https://github.com/strangerstudios/pmpro-events/pull/40 and implemented in an upcoming release. Thanks for your patience @SheraPoet
