### ISSUE TITLE
The Events Calendar: Restrict Content in List View/Calendar View 

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/pmpro-events#4]
Need to filter the display of the post content for a restricted event on the "archive" page (/events) in list or calendar view.

The Single Event is properly respecting your Advanced Setting (whether to show excerpts or hide).

**Comment by andrewlimaza** [comment]
This is working, I just find it's caching heavily but it is working on my end.

**Comment by ideadude** [comment]
If they use a transient or some kind of caching, we need to make sure it respects our filtering. Hmmm. Have to look into it more. It might require an update in TEC.

**Comment by ideadude** [comment]
Maybe the cache is working (shows the correct events to members and non-members), we just need to break it when the filter archives setting is updated.

**Comment by kimcoleman** [comment]
I am still seeing the excerpt on the list and calendar view (hover). I turned off the month view cache. I have advanced settings set to hide excerpt. Excerpt is not showing on single event view.

**Comment by kimcoleman** [comment]
Fixed in https://github.com/strangerstudios/pmpro-events/pull/23
