### ISSUE TITLE
Events in site search results

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/pmpro-events#6]
Test each integration to confirm the events in general WP site search are being properly filtered according to your Advanced Settings (include/hide from searches and archives + show/hide excerpts settings).

**Comment by kimcoleman** [comment]
All in One / Time.ly: When set to show excerpts and include in search, too much detail is showing.

All other combos appear to be fine (events are hidden from search and excerpt is hidden according to advanced settings).

**Comment by kimcoleman** [comment]
The Events Calendar: Search is all good 👍

**Comment by kimcoleman** [comment]
Events Manager: It doesn't seem that you can include events in general WP site search so this isn't an issue.

**Comment by andrewlimaza** [comment]
I've just tested Sugar Calendar and it excludes their CPT from search as of today.
