### ISSUE TITLE
Events Manager: Filter excerpt according to advanced setting.

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/pmpro-events#7]
The default events view does not include the event excerpt but it can be added using an event placeholder attribute (#_EVENTEXCERPT) in the plugin's settings.

We should try to filter this according to the membership requirements for the event and how advanced settings are configured for the site.

**Comment by andrewlimaza** [comment]
Pull Request - https://github.com/strangerstudios/pmpro-events/pull/11
