### ISSUE TITLE
Feature Request: Support for Tickets

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/pmpro-events#8]
Each supported plugin has its own method for offering "Tickets". I'll include each in the comments below. We should eventually look to support tickets purchase/registration for members only and possibly free ticketing for members.

**Comment by kimcoleman** [comment]
The Events Calendar (https://wordpress.org/plugins/the-events-calendar/) has a plugin in the repository here:
- https://wordpress.org/plugins/event-tickets/

**Comment by kimcoleman** [comment]
Events Manager has tickets built in: https://wordpress.org/plugins/events-manager/

**Comment by kimcoleman** [comment]
All in One Event Calendar (https://wordpress.org/plugins/all-in-one-event-calendar/) has a paid ticketing extension:
- https://time.ly/tickets

**Comment by kimcoleman** [comment]
Sugar Calendar (https://wordpress.org/plugins/sugar-calendar-lite/) has a free ticketing extension:
- https://wordpress.org/plugins/sugar-event-calendar-gravity-forms/

**Comment by kimcoleman** [comment]
> Events Manager has tickets built in: https://wordpress.org/plugins/events-manager/

Booking Form is properly hidden on members-only events.

**Comment by ipokkel** [comment]
Support for priced/paid tickets for non-members and free ticketing for members has been requested for the All-In-One event calendar and would be an appreciated future feature.

**Comment by andrewlimaza** [comment]
I am going to close this issue for now and revisit each ticket module independently.
